---

- include: install.yml
  tags:
    - install

- include: config
  tags:
    - config.yml
     
- name: Create virtual host
  include: vhost.yml vhost={{ item }}
  with_items:
    - "{{ vhost01 }}"
    - "{{ vhost02 }}"

- name: Deploy source code for virtual hosts
  include_tasks: deploy.yml