---
- hosts: google
  gather_facts: yes
  become: ye

  
  tasks:
    
    - name: Add Google Chrome key
      shell: wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
    - name: install google
        apt: sudo dpkg -i google-chrome-stable_current_amd64.deb