---
# Define host
- hosts: "{{hostname}}"
# Get all information  
  gather_facts: yes
# Root privileges
  become: yes
   
  tasks:
  - name: ping
    action: ping
    tags: "check-ping"
  roles:
    - ansible-role-nginx
    - php 
  