---
# Define host
- hosts: "{{hostname}}"
# Get all information  
  gather_facts: yes
# Root privileges
  become: yes
   
  tasks:
  - name: ping
    action: ping
    tags: "check-ping"
  roles:
    - role: ansible-role-nginx 
      vars:
        ansible_python_interpreter: "/usr/bin/python3" 