---
- hosts: wp
  gather_facts: yes
  become: yes
  tasks:
  - name: ping
    action: ping
  - name: show user
    shell: whoami
  - name: Install httpd
    yum:
      name: httpd
      state: latest  
    
  - name: Start httpd
    systemd:
      name: httpd
      state: started
      enable: true