---
- hosts: wp
  gather_facts: yes
  become: yes
  tasks:
  - name: ping
    action: ping
  - name: show user
    shell: whoami
  - name: Install httpd
    yum:
      name: httpd
      state: latest  
    notify: start httpd
  handlers:
  - name: start nginx
    systemd:
      name: nginx
      state: started
      enabled: true